-- Generated by Oracle SQL Developer Data Modeler 20.4.0.374.0801
--   at:        2021-04-23 14:08:05 KST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

--student ID: 29584612
--student name: Yeonsoo Kim

set echo on
SPOOL ad_schema_output.txt

DROP TABLE clinic CASCADE CONSTRAINTS;

DROP TABLE drug CASCADE CONSTRAINTS;

DROP TABLE pet CASCADE CONSTRAINTS;

DROP TABLE pet_owner CASCADE CONSTRAINTS;

DROP TABLE pet_type CASCADE CONSTRAINTS;

DROP TABLE prescription_drug CASCADE CONSTRAINTS;

DROP TABLE prescription_service CASCADE CONSTRAINTS;

DROP TABLE service CASCADE CONSTRAINTS;

DROP TABLE speciality CASCADE CONSTRAINTS;

DROP TABLE vet_speciality CASCADE CONSTRAINTS;

DROP TABLE veterinarian CASCADE CONSTRAINTS;

DROP TABLE visit CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE clinic (
    clinic_id        NUMBER(4) NOT NULL,
    clinic_name      VARCHAR2(15) NOT NULL,
    clinic_address   VARCHAR2(30) NOT NULL,
    clinic_phone_no  VARCHAR2(12) NOT NULL
);

COMMENT ON COLUMN clinic.clinic_id IS
    'Clinic''s ID';

COMMENT ON COLUMN clinic.clinic_name IS
    'Clinic''s name';

COMMENT ON COLUMN clinic.clinic_address IS
    'Clinic''s address';

COMMENT ON COLUMN clinic.clinic_phone_no IS
    'Clinic''s phone number';

ALTER TABLE clinic ADD CONSTRAINT clinic_pk PRIMARY KEY ( clinic_id );

CREATE TABLE drug (
    drug_id           NUMBER(3) NOT NULL,
    drug_name         VARCHAR2(20) NOT NULL,
    drug_cost         NUMBER(8, 2) NOT NULL,
    drug_instruction  VARCHAR2(100) NOT NULL
);

COMMENT ON COLUMN drug.drug_id IS
    'Drug''s ID';

COMMENT ON COLUMN drug.drug_name IS
    'Drug''s name';

COMMENT ON COLUMN drug.drug_cost IS
    'Drug''s cost';

COMMENT ON COLUMN drug.drug_instruction IS
    'Drug''s instruction';

ALTER TABLE drug ADD CONSTRAINT drug_pk PRIMARY KEY ( drug_id );

CREATE TABLE pet (
    pet_id        NUMBER(4) NOT NULL,
    pettype_id    NUMBER(4) NOT NULL,
    owner_id      NUMBER(4) NOT NULL,
    pet_gender    CHAR(1) NOT NULL,
    pet_name      VARCHAR2(15),
    pet_type      VARCHAR2(30) NOT NULL,
    pet_dob       DATE,
    pet_deceased  CHAR(1) DEFAULT 'N' NOT NULL
);

ALTER TABLE pet
    ADD CONSTRAINT chk_pet_gender CHECK ( pet_gender IN ( 'F', 'M' ) );

ALTER TABLE pet
    ADD CONSTRAINT chk_pet_deceased CHECK ( pet_deceased IN ( 'N', 'Y' ) );

COMMENT ON COLUMN pet.pet_id IS
    'Pet''s ID';

COMMENT ON COLUMN pet.pettype_id IS
    'ID of pet type (Surrogate Key)';

COMMENT ON COLUMN pet.owner_id IS
    'Pet owner''s ID';

COMMENT ON COLUMN pet.pet_gender IS
    'Pet''s Gender';

COMMENT ON COLUMN pet.pet_name IS
    'Pet''s name';

COMMENT ON COLUMN pet.pet_type IS
    'Pet''s type';

COMMENT ON COLUMN pet.pet_dob IS
    'Pet''s date of birth';

COMMENT ON COLUMN pet.pet_deceased IS
    'Pet is deceased or not';

ALTER TABLE pet ADD CONSTRAINT pet_pk PRIMARY KEY ( pet_id );

CREATE TABLE pet_owner (
    owner_id        NUMBER(4) NOT NULL,
    owner_gname     VARCHAR2(15) NOT NULL,
    owner_fname     VARCHAR2(15) NOT NULL,
    owner_street    VARCHAR2(30) NOT NULL,
    owner_town      VARCHAR2(15) NOT NULL,
    owner_postcode  CHAR(4) NOT NULL,
    owner_phone_no  VARCHAR2(12)
);

COMMENT ON COLUMN pet_owner.owner_id IS
    'Pet owner''s ID';

COMMENT ON COLUMN pet_owner.owner_gname IS
    'Pet owner''s given name';

COMMENT ON COLUMN pet_owner.owner_fname IS
    'Pet owner''s family name';

COMMENT ON COLUMN pet_owner.owner_street IS
    'Pet owner''s street address';

COMMENT ON COLUMN pet_owner.owner_town IS
    'Pet owner''s town address';

COMMENT ON COLUMN pet_owner.owner_postcode IS
    'Pet owner''s postcode address';

COMMENT ON COLUMN pet_owner.owner_phone_no IS
    'Pet owner''s phone number';

ALTER TABLE pet_owner ADD CONSTRAINT pet_owner_pk PRIMARY KEY ( owner_id );

CREATE TABLE pet_type (
    pettype_id    NUMBER(4) NOT NULL,
    pettype_name  VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN pet_type.pettype_id IS
    'ID of pet type (Surrogate Key)';

COMMENT ON COLUMN pet_type.pettype_name IS
    'The name of the Pet type';

ALTER TABLE pet_type ADD CONSTRAINT pet_type_pk PRIMARY KEY ( pettype_id );

ALTER TABLE pet_type ADD CONSTRAINT pet_type_nk UNIQUE ( pettype_name );

CREATE TABLE prescription_drug (
    pd_id            NUMBER(4) NOT NULL,
    drug_id          NUMBER(3) NOT NULL,
    visit_id         NUMBER(6) NOT NULL,
    pd_qty_supplied  NUMBER(3) NOT NULL,
    pd_frequency     VARCHAR2(30),
    pd_drug_dose     VARCHAR2(30),
    pd_cost          NUMBER(8, 2) NOT NULL
);

COMMENT ON COLUMN prescription_drug.pd_id IS
    'Drug prescription ID (Surrogate Key)';

COMMENT ON COLUMN prescription_drug.drug_id IS
    'Drug''s ID';

COMMENT ON COLUMN prescription_drug.visit_id IS
    'Visit''s ID (Surrogate Key)';

COMMENT ON COLUMN prescription_drug.pd_qty_supplied IS
    'Quantity of prescribed drug';

COMMENT ON COLUMN prescription_drug.pd_frequency IS
    'Frequency instruction for drug prescription';

COMMENT ON COLUMN prescription_drug.pd_drug_dose IS
    'Used Drug dose of a drug prescription';

COMMENT ON COLUMN prescription_drug.pd_cost IS
    'The cost of drug prescription';

ALTER TABLE prescription_drug ADD CONSTRAINT prescription_drug_pk PRIMARY KEY ( pd_id );

ALTER TABLE prescription_drug ADD CONSTRAINT prescription_drug_nk UNIQUE ( drug_id,
                                                                           visit_id );

CREATE TABLE prescription_service (
    ps_id         NUMBER(4) NOT NULL,
    visit_id      NUMBER(6) NOT NULL,
    service_code  CHAR(5) NOT NULL,
    ps_cost       NUMBER(8, 2) NOT NULL
);

COMMENT ON COLUMN prescription_service.ps_id IS
    'Service prescription ID (Surrogate Key)';

COMMENT ON COLUMN prescription_service.visit_id IS
    'Visit''s ID (Surrogate Key)';

COMMENT ON COLUMN prescription_service.service_code IS
    'Code (ID) of the Service';

COMMENT ON COLUMN prescription_service.ps_cost IS
    'The cost of the service prescription';

ALTER TABLE prescription_service ADD CONSTRAINT prescription_service_pk PRIMARY KEY (
ps_id );

ALTER TABLE prescription_service ADD CONSTRAINT prescription_service_nk UNIQUE (
service_code,
                                                                                 visit_id );

CREATE TABLE service (
    service_code         CHAR(5) NOT NULL,
    service_description  VARCHAR2(50) NOT NULL,
    service_cost         NUMBER(8, 2) NOT NULL
);

COMMENT ON COLUMN service.service_code IS
    'Code (ID) of the Service';

COMMENT ON COLUMN service.service_description IS
    'Description of the Service';

COMMENT ON COLUMN service.service_cost IS
    'Cost of the service';

ALTER TABLE service ADD CONSTRAINT service_pk PRIMARY KEY ( service_code );

CREATE TABLE speciality (
    spec_id    NUMBER(3) NOT NULL,
    spec_name  VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN speciality.spec_id IS
    'Speciality''s ID (Surrogate Key)';

COMMENT ON COLUMN speciality.spec_name IS
    'Speciality name';

ALTER TABLE speciality ADD CONSTRAINT speciality_pk PRIMARY KEY ( spec_id );

ALTER TABLE speciality ADD CONSTRAINT speciality_nk UNIQUE ( spec_name );

CREATE TABLE vet_speciality (
    vet_id   NUMBER(4) NOT NULL,
    spec_id  NUMBER(3) NOT NULL
);

COMMENT ON COLUMN vet_speciality.vet_id IS
    'Vet''s ID';

COMMENT ON COLUMN vet_speciality.spec_id IS
    'Speciality''s ID (Surrogate Key)';

ALTER TABLE vet_speciality ADD CONSTRAINT vet_speciality_pk PRIMARY KEY ( spec_id,
                                                                          vet_id );

CREATE TABLE veterinarian (
    vet_id             NUMBER(4) NOT NULL,
    clinic_id          NUMBER(4) NOT NULL,
    vet_gname          VARCHAR2(15) NOT NULL,
    vet_fname          VARCHAR2(15) NOT NULL,
    vet_phone_no       VARCHAR2(12),
    vet_date_employed  DATE NOT NULL,
    vet_count          NUMBER(3) NOT NULL
);

COMMENT ON COLUMN veterinarian.vet_id IS
    'Vet''s ID';

COMMENT ON COLUMN veterinarian.clinic_id IS
    'Clinic''s ID';

COMMENT ON COLUMN veterinarian.vet_gname IS
    'Vet''s given name';

COMMENT ON COLUMN veterinarian.vet_fname IS
    'Vet''s family name';

COMMENT ON COLUMN veterinarian.vet_phone_no IS
    'Vet''s phone number';

COMMENT ON COLUMN veterinarian.vet_date_employed IS
    'Vet''s the first  employed date';

COMMENT ON COLUMN veterinarian.vet_count IS
    'Count of not-home-clinic visits';

ALTER TABLE veterinarian ADD CONSTRAINT veterinarian_pk PRIMARY KEY ( vet_id );

CREATE TABLE visit (
    visit_id         NUMBER(6) NOT NULL,
    visit_datetime   DATE NOT NULL,
    vet_id           NUMBER(4) NOT NULL,
    pet_id           NUMBER(4) NOT NULL,
    visit_length     NUMBER(3) NOT NULL,
    visit_note       VARCHAR2(100),
    visit_cost       NUMBER(8, 2) NOT NULL,
    visit_paymethod  VARCHAR2(4) NOT NULL,
    first_visit_id   NUMBER(6) NOT NULL
);

ALTER TABLE visit
    ADD CONSTRAINT chk_visit_paymethod CHECK ( visit_paymethod IN ( 'CASH', 'EFT' ) );

COMMENT ON COLUMN visit.visit_id IS
    'Visit''s ID (Surrogate Key)';

COMMENT ON COLUMN visit.visit_datetime IS
    'The date and time of a Visit';

COMMENT ON COLUMN visit.vet_id IS
    'Vet''s ID';

COMMENT ON COLUMN visit.pet_id IS
    'Pet''s ID';

COMMENT ON COLUMN visit.visit_length IS
    'The length of a Visit in minute';

COMMENT ON COLUMN visit.visit_note IS
    'Note(Description)  of a Visit';

COMMENT ON COLUMN visit.visit_cost IS
    'The cost  of a Visit';

COMMENT ON COLUMN visit.visit_paymethod IS
    'Payment method  of a Visit';

COMMENT ON COLUMN visit.first_visit_id IS
    'Visit''s ID (Surrogate Key)';

ALTER TABLE visit ADD CONSTRAINT visit_pk PRIMARY KEY ( visit_id );

ALTER TABLE visit ADD CONSTRAINT visit_nk UNIQUE ( visit_datetime,
                                                   vet_id );

ALTER TABLE veterinarian
    ADD CONSTRAINT clinic_veterinarian FOREIGN KEY ( clinic_id )
        REFERENCES clinic ( clinic_id );

ALTER TABLE prescription_drug
    ADD CONSTRAINT drug_prescription_drug FOREIGN KEY ( drug_id )
        REFERENCES drug ( drug_id );

ALTER TABLE pet
    ADD CONSTRAINT pet_owner_pet FOREIGN KEY ( owner_id )
        REFERENCES pet_owner ( owner_id );

ALTER TABLE pet
    ADD CONSTRAINT pet_type_pet FOREIGN KEY ( pettype_id )
        REFERENCES pet_type ( pettype_id );

ALTER TABLE visit
    ADD CONSTRAINT pet_visit FOREIGN KEY ( pet_id )
        REFERENCES pet ( pet_id );

ALTER TABLE prescription_service
    ADD CONSTRAINT service_prescription_service FOREIGN KEY ( service_code )
        REFERENCES service ( service_code );

ALTER TABLE vet_speciality
    ADD CONSTRAINT speciality_vet_speciality FOREIGN KEY ( spec_id )
        REFERENCES speciality ( spec_id );

ALTER TABLE vet_speciality
    ADD CONSTRAINT veterinarian_vet_speciality FOREIGN KEY ( vet_id )
        REFERENCES veterinarian ( vet_id );

ALTER TABLE visit
    ADD CONSTRAINT veterinarian_visit FOREIGN KEY ( vet_id )
        REFERENCES veterinarian ( vet_id );

ALTER TABLE visit
    ADD CONSTRAINT visit_first_visit FOREIGN KEY ( first_visit_id )
        REFERENCES visit ( visit_id );

ALTER TABLE prescription_drug
    ADD CONSTRAINT visit_prescription_drug FOREIGN KEY ( visit_id )
        REFERENCES visit ( visit_id );

ALTER TABLE prescription_service
    ADD CONSTRAINT visit_prescription_service FOREIGN KEY ( visit_id )
        REFERENCES visit ( visit_id );

SPOOL off
set echo off


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             0
-- ALTER TABLE                             32
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
